config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subjects
  resources :teachers
  resources :courses
  resources :departments

  get 'signup', to: 'users#new'
  resources :users, except: [:new]  #ya que new lo he usado en la linea de arriba

  #Ahora, para que localhost:3000/login tenga una ruta, se la creo. Esto es:
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #donde recuerdo, sessions es la parte de controler y new es la action que va a hacer.


end

app/models/department.rb
class Department < ApplicationRecord

  has_many :teachers

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  before_action :set_department, only: [:edit, :update, :show, :destroy]

  def index
    @department = Department.all
  end

  def new
    @department = Department.new

    respond_to do |format|     # como le he puesto un remote en el link de new subject, tenemos dos casuisticas:
      format.html              # el html de siempre, sin el remote en el link
      format.js                # generar un javascript con el formulario.
    end
  end

  def show
  end

  def edit
  end

  def create
    @department = Department.new(department_params)
    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'El departamento ha sido creado correctamente' }
        format.js
        format.json { render json: @department, status: :created, location: @users}
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @department.update(department_params)
      flash[:success] = "El departamento se ha modificado correctamente"
      redirect_to department_path(@department)
    else
      render 'edit'
    end
  end

  def destroy
    @department.destroy
    flash[:danger] = "El departamento ha sido eliminado"   #cambio los flash danger sale en rojo
    redirect_to departments_path
  end


  private

  # Aquí defino métodos para pasar parámetros en el primer caso, para ahorrar código en el segundo.
  def department_params
    params.require(:department).permit(:name, teacher_ids: [])
  end

  def set_department
    @department = Department.find(params[:id])  #esta línea se repetía en los métodos de arriba.
  end

end

app/views/departments/_form.html.erb
<%= form_for @department do |f| %>
  <form>
    <div class="form-group">
      <b><label for="formGroupExampleInput"> Departamento </label></b>
      <%= f.text_field :name, class: 'form-control', placeholder: "Nombre del departamento" %>
    </div>
    <div>
      <b><label for="formGroupExampleInput"> Selecciona los profesores que componen el nuevo departamento </label></b>
      <ul class="list-group">
        <li class="list-group-item"><%= f.collection_check_boxes :teacher_ids, Teacher.all, :id, :name %><br></li>
      </ul>
    </div>
    <%= f.submit "Actualizar", class: "btn btn-primary" %>
  </form>
<% end %>

app/views/departments/create.js.erb
$("<%= escape_javascript(render @department) %>").appendTo("#department");
$("#form_new").html(" ");
$("#tabladepartamentos").append("<tr><td>@department</td></tr>");

app/views/departments/edit.html.erb
<h1> Edita el departamento de <%= @department.name %> </h1>


<%= render 'form' %>

app/views/departments/index.html.erb
<div class="body" id="tabladepartamentos">
  <div align="center">
    <h3> Departamentos </h3>

    <% @department.each do |department| %>
      <button type="button" class="btn btn-outline-secondary margin">
        <%= link_to department.name, department_path(department) %>
      </button>
    <% end %>
  </div>
  <% if current_user&.admin? %>
   <button type="button" class="btn btn-outline-info"> <%= link_to "Agregar un nuevo departamento", new_department_path, remote:true %></button>
  <%end%>
</div>

<div id="form_new">   <!-- id="form_new, identifica mi div aquí, usaré "#form_new" para saber que es aquí donde va el formulario"-->
</div>

app/views/departments/new.html.erb
<h2> Introducir un nuevo departamento </h2>


<%= render 'form' %>

app/views/departments/new.js.erb
$("#form_new").html('<%= j(render("form")) %>');

app/views/departments/show.html.erb
<div>
  <%= @department.name %>
</div>



<button type="button" class="btn btn-success"> <%= link_to " Ver todos los departamentos ", departments_path %> </button>
<% if current_user&.admin? %>
  <button type="button" class="btn btn-warning">  <%= link_to "Editar departamento ",  edit_department_path(@department) %> </button>
  <button type="button" class="btn btn-danger">  <%= link_to "Eliminar departamento ", department_path(@department), method: :delete, data: { confirm: "¿Estás seguro que quieres eliminar este departamento?"}
  %> </button>
<%end%>