config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subjects
  resources :teachers
  resources :courses
  resources :departments

  get 'signup', to: 'users#new'
  resources :users, except: [:new]  #ya que new lo he usado en la linea de arriba

  #Ahora, para que localhost:3000/login tenga una ruta, se la creo. Esto es:
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #donde recuerdo, sessions es la parte de controler y new es la action que va a hacer.


end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :subject_teachers
  has_many :teachers, through: :subject_teachers

  has_many :course_subjects
  has_many :courses, through: :course_subjects

  #Añadrié más validaciones conforme lo vaya necesitando: p.ej que esté el usuario registrado.
  validates :name, presence:true, length: { minimum: 3, maximum: 50 }  #para que no haya asignaturas en blanco o inexistentes

end

app/controllers/subjects_controller.rb
# Desde el controlador me voy creando mis metodos poco a poco junto con los html. Lo primero que hago es irme
# al fichero de routes para añadir en este caso resources routes :subjects y esto me genera lo que necesito para los
# links.

class SubjectsController < ApplicationController

  before_action :set_subject, only: [:edit, :update, :show, :destroy]

  def index
    @subject = Subject.all
  end

  def new
    @subject = Subject.new

    respond_to do |format|     # como le he puesto un remote en el link de new subject, tenemos dos casuisticas:
      format.html              # el html de siempre, sin el remote en el link
      format.js                # generar un javascript con el formulario.
    end
  end

  def show
    #@subject = Subject.find(params[:id])
  end

  def edit
    #@subject = Subject.find(params[:id])
  end

  def create
    @subject = Subject.new(subject_params)
    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'La asignatura se ha añadido correctamente' }
        format.js
        format.json { render json: @subject, status: :created, location: @subjects}
        #redirect_to subjects_path(@subject)
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #@subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      flash[:success] = "La asignatura se ha modificado correctamente"
      redirect_to subject_path(@subject)
    else
      render 'edit'
    end
  end

  def destroy
    #@subject = Subject.find(params[:id])
    @subject.destroy
    flash[:danger] = "La asignatura ha sido eliminada"   #cambio los flash danger sale en rojo
    redirect_to subjects_path
  end


  private

  # Aquí defino métodos para pasar parámetros en el primer caso, para ahorrar código en el segundo.
  def subject_params
    params.require(:subject).permit(:name, course_ids: [], teacher_ids: [])
  end

  def set_subject
    @subject = Subject.find(params[:id])  #esta línea se repetía en los métodos de arriba.
  end

end

app/views/subjects/_form.html.erb
<%= render 'shared/errors', obj: @subject %> <!-- aquí especifico quién es obj.-->

<%= form_for @subject do |f| %>
  <form>
    <div class="form-group">
      <label for="formGroupExampleInput"> <b>Asignatura</b> </label>
      <%= f.text_field :name, class: 'form-control', placeholder: "Introduce la asignatura" %>
    </div>
    <!-- para hacer la asociación muestro al usuario las opciones que van ligada a cada asignatura-->
    <p><b> Selecciona los cursos en los que será impartida</b></p>
    <div>
      <ul class="list-group">
        <li class="list-group-item">
          <%= f.collection_check_boxes :course_ids, Course.all, :id, :secondary %><br>
        </li>
      </ul>
    </div>
    <p><b> Selecciona a los docentes que la impartirán </b></p>
    <div>
      <ul class="list-group">
        <li class="list-group-item">
          <%= f.collection_check_boxes :teacher_ids, Teacher.all, :id, :name %><br>
        </li>
      </ul>
    </div>
    <%= f.submit "Actualizar", class: "btn btn-primary" %>
  </form>
<% end %>

app/views/subjects/create.js.erb
$("<%= escape_javascript(render @subject) %>").appendTo("#subject");
$("#form_new").html(" ");
$("#customers").append("<tr><td>@subject</td></tr>");

app/views/subjects/edit.html.erb
<h1> Modifica la asignatura <%=@subject.name %> </h1>


<%= render 'form' %>

app/views/subjects/index.html.erb
<h1 align="center"> Asignaturas </h1>

  <table id="customers">
    <tr>
      <th>
        Asignatura
      </th>
      <th>
        Profesores
      </th>
      <th>
        Cursos
      </th>
    </tr>
    <!-- Los muestro en la tabla ordenados alfabéticamente -->
    <% @subject.order("name").each do |subject| %>
      <tr>
    <td>
      <%= link_to subject.name, subject_path(subject) %>
    </td>
    <td>
      <% subject.teachers.each do |teacher| %>
      <%= link_to teacher.name, teacher_path(teacher) %>  |
      <%end%>
    </td>
    <td>
      <% subject.courses.each do |course| %>
      <%= link_to course.secondary, course_path(course) %>  |
      <%end%>
    </td>
  </tr>
    <% end %>
  </table>

<% if current_user&.admin? %>
  <button type="button" class="btn btn-success"> <%= link_to "Añadir una nueva asignatura", new_subject_path, remote: true %></button>
  <div id="form_new">   <!-- id="form_new, identifica mi div aquí, usaré "#form_new" para saber que es aquí donde va el formulario"-->
  </div>
<%end%>

app/views/subjects/new.html.erb
<h2> Introducir una nueva asignatura </h2>

<%= render 'form' %>

app/views/subjects/new.js.erb
$("#form_new").html('<%= j(render("form")) %>');

app/views/subjects/show.html.erb
<b><i> Información de <%= @subject.name %> </i></b>


<table id="customers">
  <tr>
    <td>
      <b><p> Se imparte en los cursos: </p></b>
      <ul>
        <% @subject.courses.each do |course| %>
          <li><%= link_to course.secondary, course_path(course) %><br></li>
        <% end %>
      </ul>
    </td>
  </tr>
</table>

<table id="customers">
  <tr>
    <td>
      <b><p> Los profesores que la imparten son: </p></b>
      <ul>
        <% @subject.teachers.each do |teacher| %>
          <li><%= link_to teacher.name, teacher_path(teacher) %><br></li>
        <% end %>
      </ul>
    </td>
  </tr>
</table>


<button type="button" class="btn btn-success">  <%= link_to " Volver a la lista de asignaturas ", subjects_path %> </button>
<% if current_user&.admin? %>
  <button type="button" class="btn btn-warning"> <%= link_to "Editar asignatura ",  edit_subject_path(@subject) %> </button>
  <button type="button" class="btn btn-danger"> <%= link_to "Eliminar asignatura ", subject_path(@subject), method: :delete,
                                                            data: { confirm: "¿Estás seguro que quieres eliminar esta asignatura?"} %> </button>
<%end%>