config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subjects
  resources :teachers
  resources :courses
  resources :departments

  get 'signup', to: 'users#new'
  resources :users, except: [:new]  #ya que new lo he usado en la linea de arriba

  #Ahora, para que localhost:3000/login tenga una ruta, se la creo. Esto es:
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #donde recuerdo, sessions es la parte de controler y new es la action que va a hacer.


end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :subject_teachers
  has_many :subjects, through: :subject_teachers

  has_many :course_teachers
  has_many :courses, through: :course_teachers

  belongs_to :department

  belongs_to :user

  validates :name, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 105 }
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  before_action :set_teacher, only: [:edit, :update, :show, :destroy]

  def index
    @teacher = Teacher.all
  end

  def new
    @teacher = Teacher.new

    respond_to do |format|     # como le he puesto un remote en el link de new subject, tenemos dos casuisticas:
      format.html              # el html de siempre, sin el remote en el link
      format.js                # generar un javascript con el formulario.
    end
  end

  def show
    #@teacher = Teacher.find(params[:id])
  end

  def edit
    #@teacher = Teacher.find(params[:id])
  end

  def create
    @teacher = Teacher.new(teacher_params)
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'El perfil se ha creado correctamente' }
        format.js
        format.json { render json: @teacher, status: :created, location: @teacher}
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #@teacher = Teacher.find(params[:id])
    if @teacher.update(teacher_params)
      flash[:success] = "El nombre del profesor se ha modificado correctamente"
      redirect_to teacher_path(@teacher)
    else
      render 'edit'
    end
  end

  def destroy
    #@teacher = Teacher.find(params[:id])
    @teacher.destroy
    flash[:danger] = "El profesor ha sido eliminado"   #cambio los flash danger sale en rojo
    redirect_to teachers_path
  end

  private

    def teacher_params
      params.require(:teacher).permit(:name, :responsibility, :department_id, :user_id, course_ids: [], subject_ids: [])
    end

    def set_teacher
      @teacher = Teacher.find(params[:id])  #esta línea se repetía en los métodos de arriba.
    end
end



  #ajax
  #    formularios con ajax: primero me vengo al controlador de donde esté el formulario y modifico los metodos
  #    ne w y create. despues me creo un new.js.erb y un create.js.erb donde añado el codigo que tengo
  #    en este proyecto custumers es el nombre de la tabla en la que aparece la info de donde se ha realizado
  #    el cuestionario. Tb saber que antes de tocar estos archivos debo poner remote en los link donde abajo aparecera
  #    el formulario

app/views/teachers/_form.html.erb
<%= render 'shared/errors', obj: @teacher %> <!-- aquí especifico quién es obj.-->

<!-- Hago un partial de edit y new -->

<%= form_for @teacher do |f| %>
  <form>
    <div class="form-group">
      <label for="formGroupExampleInput"> <b>Nombre del docente</b> </label>
      <%= f.text_field :name, class: 'form-control', placeholder: "Nombre del profesor" %>
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput"> <b>Responsabilidad</b> </label>
      <%= f.text_field :responsibility, class: 'form-control',  placeholder: "Responsabilidad" %>
    </div>
    <p><b> Selecciona el Departamento al que pertenece </b></p>
    <div>
      <ul class="list-group">
        <li class="list-group-item"><%= f.select :department_id, options_from_collection_for_select(Department.all, :id, :name, @teacher.department_id) %><br></li>
      </ul>
    </div>
    <p><b> Selecciona los cursos a los que da clase </b></p>
    <div>
      <ul class="list-group">
        <li class="list-group-item"><%= f.collection_check_boxes :course_ids, Course.all, :id, :secondary %><br></li>
      </ul>
    </div>
    <p><b> Selecciona las asignaturas que imparte </b></p>
    <div>
      <ul class="list-group">
        <li class="list-group-item"><%= f.collection_check_boxes :subject_ids, Subject.all, :id, :name %><br></li>
      </ul>
    </div>
    <p><b> Selecciona su nombre de usuario </b></p>
    <div>
      <ul class="list-group">
        <li class="list-group-item"><%= f.select :user_id, options_from_collection_for_select(User.all, :id, :username, @teacher.user_id) %><br></li>
      </ul>
    </div>
    <!-- <button type="submit" class="btn btn-primary"> Añadir </button> -->
    <%= f.submit "Actualizar", class: "btn btn-primary" %>
  </form>
  <%= link_to " Volver a la lista de profesores ", teachers_path %>
<% end %>

app/views/teachers/_teacher.html.erb
  <%= link_to teacher.name, teacher_path(teacher)%><br>

app/views/teachers/create.js.erb
$("<%= escape_javascript(render @teacher) %>").appendTo("#teacher");
$("#form_new").html(" ");
$("#customers").append("<tr><td>@teacher</td></tr>");

app/views/teachers/edit.html.erb
<h1> Edita el perfil de <%=@teacher.name %> </h1>

<%= render 'form' %>

app/views/teachers/index.html.erb
<h1 align="center"> Profesores </h1>

<table id="customers">
  <tr>
    <th>
      Profesores
    </th>
    <th>
      Responsabilidad
    </th>
    <th>
      Departamento
    </th>
  </tr>
  <!-- Los ordeno alfabéticamente -->
  <% @teacher.order("name").each do |teacher| %>
    <tr>
      <td>
        <%= link_to teacher.name, teacher_path(teacher) %>
      </td>
      <td>
        <%= link_to teacher.responsibility, teacher_path(teacher) %>
      </td>
      <td>
        <%= link_to teacher.department&.name, departments_path %>
      </td>
    </tr>
  <% end %>
</table>

<%# - raise  %>
<% if current_user&.admin? %>
  <button type="button" class="btn btn-success"> <%= link_to "Agregar un nuevo profesor", new_teacher_path %></button>
  <div id="form_new">   <!-- id="form_new, identifica mi div aquí, usaré "#form_new" para saber que es aquí donde va el formulario"-->
  </div>
<%end%>

app/views/teachers/new.html.erb
<h2> Incluir un nuevo docente a la lista </h2>

<!-- #código en _form.-->

  <%= render 'form' %>

app/views/teachers/new.js.erb
$("#form_new").html('<%= j(render("form")) %>');

app/views/teachers/show.html.erb
<b><i> Perfil de <%= @teacher.name %> </i></b>


<table id="customers">
  <tr>
    <td>
      <b><p> Imparte clase en: </p></b>
     <ul>
        <% @teacher.courses.each do |course| %>
           <li><%= link_to course.secondary, course_path(course) %><br></li>
        <% end %>
      </ul>
    </td>
  </tr>
</table>

<table id="customers">
  <tr>
    <td>
      <b><p> Imparte las asignaturas: </p></b>
      <ul>
        <% @teacher.subjects.each do |subject| %>
          <li><%= link_to subject.name, subject_path(subject) %><br></li>
        <% end %>
      </ul>
    </td>
  </tr>
</table>



<button type="button" class="btn btn-success"> <%= link_to " Volver a la lista de profesores ", teachers_path %> </button>
<% if current_user&.admin? %>
  <button type="button" class="btn btn-warning">  <%= link_to "Editar perfil ",  edit_teacher_path(@teacher) %> </button>
  <button type="button" class="btn btn-danger">  <%= link_to "Eliminar perfil ", teacher_path(@teacher), method: :delete,  data: { confirm: "¿Estás seguro que quieres eliminar este perfil?"}
                                                     %> </button>
<%end%>