config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subjects
  resources :teachers
  resources :courses
  resources :departments

  get 'signup', to: 'users#new'
  resources :users, except: [:new]  #ya que new lo he usado en la linea de arriba

  #Ahora, para que localhost:3000/login tenga una ruta, se la creo. Esto es:
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #donde recuerdo, sessions es la parte de controler y new es la action que va a hacer.


end

app/views/layouts/_messages.html.erb
<!-- Código sacado de internet bootstrap 4 grid -->

<div class="row">
  <div class="col-sm">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navegation.html.erb
<!-- Cojo código de https://getbootstrap.com/docs/4.0/components/navbar/ para crear mi navegador. Lo voy adornando
con los estilos que vaya poniendo en custom. -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Instituto", root_path, class: "navbar-brand", id:"logo" %>
  <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Asignaturas", subjects_path, class: "nav-link" %>
        <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Profesores", teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Usuarios", users_path, class: "nav-link" %>
        <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Departamentos", departments_path, class: "nav-link" %>
        <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="courses_path" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Cursos
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <!-- No me deja hacer el código que tengo comentado-->
          <%#  @course.each do |secondary| %>
            <%#= link_to "#{course.secondary}", courses_path(course), class: "dropdown-item" %>
          <%# end %>
          <%= link_to "Secundaria", courses_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Primero", course_path(Course.find(1)), class: "dropdown-item" %>
          <%= link_to "Segundo", course_path(Course.find(2)), class: "dropdown-item" %>
          <%= link_to "Tercero", course_path(Course.find(3)), class: "dropdown-item" %>
          <%= link_to "Cuarto", course_path(Course.find(4)), class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0 nav-item dropdown">
      <% if logged_in? %>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Perfil
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Editar perfil", edit_user_path(current_user), class:"dropdown-item" %>
          <%= link_to "Ver perfil", user_path(current_user), class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Eliminar perfil ", user_path(current_user), method: :delete,  class:"dropdown-item", data: { confirm: "¿Estás seguro que quieres eliminar este perfil?"}%>
        </div>
        <%= link_to 'Cerrar Sesión', logout_path, method: :delete, class:"nav-link" %> <!-- Log out de la barra de navegación-->
      <% else %>
          <%= link_to 'Iniciar Sesión', login_path,  class:"nav-link" %> <!-- Log out de la barra de navegación-->
          <%= link_to 'Registrarse', signup_path, class:"nav-link" %> <!-- Log out de la barra de navegación-->
      <%end %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practica</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- ahora voy a crear un render layouts/navegation para que este archivo sea lo más limpio posible y llevar el
    código hacia el nuevo archivo que voy a crear _navegation.html.erb -->
    <%= render 'layouts/navegation' %>

    <%= render 'layouts/messages' %>

    <!-- Añado el container que le va a dar un espacio a lo que aparece ALPHA BLOG en localhost:3000 -->
    <div class="container">
       <%= yield %>
    </div>
  </body>
</html>